### PR TITLE
Modularizes Echo, "Ports" Phytosians

### PR DESCRIPTION
**Pull request by Ms-Mee**
## About The Pull Request
"Ports" Phytosians from Yogs, that is to say replaces podpeople with my take on them and makes them roundstart.

Modularizes the files I've changed in the past to take us off future marg conflict hell.

- [x] ~~Phytosian lore~~ Later
- [x] ~~Rebalancing, they're weird and feel a little too strong presently~~ Later
- [x] Make sure the modular folder works properly
- [x] ~~Fix tests~~
- [x] Do whatever else I am told to achieve

## Why It's Good For The Game
Modular folder, interesting new species.

## Changelog

:cl:
add: phytosian hairs, lungs and wings
code: changed podpeople code and related sprite accessories
code: changed breathing code
code: modularized my changes to echo, others' not yet
config: roundstart plant
imageadd: phytosian hairs, lungs and wings
/:cl:

### CODE REVIEW

**Comment by Ms-Mee** [comment]
It's so joever(When I'm done with it I'll do prefs stuff since I don't have classes currently)

**Comment by Ms-Mee** [comment]
"Gonna finish it tomorrow"

The devilish human nervous and immunological systems about to ruin my plans:

**Comment by Ms-Mee** [comment]
I do miss having a desk, it forced me to not be lazy on the computer

**Comment by Ms-Mee** [comment]
THE NEFARIOUS TGS

**Comment by Ms-Mee** [comment]
image

**Comment by Ms-Mee** [comment]
Can't wait to be told I did it wrong

**Comment by Ms-Mee** [comment]
Linters... My mortal enemy...

**Comment by Ms-Mee** [comment]
Wait why did it revert that changelog commit what

**Comment by Ms-Mee** [comment]
Doing time travel shenanigans don't worry about it

**Comment by Ms-Mee** [comment]
image

**Comment by Ms-Mee** [comment]
I'll do the changes I plan on later today if this is indeed how modularization should be, and then start the prefs things (horror)

**Comment by Ms-Mee** [comment]
Desire for Approval (or Approval Desire) by Aiobahn.mp3

**Comment by TheNeoGamer42** [comment]
There a reason you have the echo specific defines in the code folder and not the echo13 folder?

**Comment by Ms-Mee** [comment]
Defines only work for code that appears after them, so that is where a modular define folder goes even if presently it doesn't matter, better having it where it should be now than having to move the whole folder later

**Comment by Ms-Mee** [comment]
Gonna leave vampire phytosians to way later because it's just not gonna work the way I want for now

Also trying an echo dme replacement so we don't get dme merge conflicts later and such

**Comment by Ms-Mee** [comment]
Wait did I trick myself into modularizing vampires now with the prospect of vampire phytosians but then decide to not do vampire phytosians what the hell

**Comment by Ms-Mee** [comment]
Although sap blood means I kinda had to anyways

**Comment by Ms-Mee** [comment]
My form empties

**Comment by Ms-Mee** [comment]
One can hope everything works right and fine (it won't)

**Comment by Ms-Mee** [comment]
Not gonna change this further other than eventual lore unless I run into something I missed while testing backstories and languages so

**Comment by Ms-Mee** [comment]
image

**Pull request merged**
