### PR TITLE
Shiptest Mirror #5 [MDB IGNORE]

### PR DESCRIPTION
**Pull request by Ms-Mee**
## About The Pull Request
Merges Shiptest's latest changes while addressing issues in any modular files (I'll explain what one needs to do when mirroring later, ideally with a readme on the modular folder).

All changes I personally made were tested.

## Why It's Good For The Game
Parity and functionality.

## Changelog

:cl:
code: Vampirism blood level tracking now uses signals, same way the species was changed to behave
code: Unmirrored new_player.dm, changed cryopod logic
/:cl:

### CODE REVIEW

**Comment by Ms-Mee** [comment]
Map failure, I'll have a look when I wake up

**Comment by Ms-Mee** [comment]
Fixed

**Comment by TheNeoGamer42** [comment]
why do we even have the mapdiffbot and why is it breaking now

**Comment by Ms-Mee** [comment]
I don't know but this should be fine to merge regardless

**Comment by Ms-Mee** [comment]
Wheelchairs are back

**Comment by Ms-Mee** [comment]
image

**Comment by Ms-Mee** [comment]
Checks passed image

**Comment by TheNeoGamer42** [comment]
speedmerge time

**Pull request merged**
