### PR TITLE
Return of the morbius real (fake) (real)

### PR DESCRIPTION
**Pull request by Ms-Mee**
## About The Pull Request

Returns the vampire quirk, I might've forgotten something I'll check again tomorrow when I'm not as sleep deprived as I am.

## Why It's Good For The Game

Everyone loves the hit movie morbius

## Changelog

:cl:
add: Readds the vampire quirk and draculine bloodtype
/:cl:

### CODE REVIEW

**Comment by Ms-Mee** [comment]
Linters (evil)

**Review by Ms-Mee — COMMENTED** [review]
Seems fine now, removed permanent hunger delay that would appear due to the spawn stuff running before quirks are assigned, if this causes issues I haven't found them messing around

**Comment by TheNeoGamer42** [comment]
half tempted to say make it start  you with less blood, but yeah, good catch

**Comment by Ms-Mee** [comment]
Starting blood amount is low enough unless one wants people dying in 10 minutes, blood kills you, hunger does not

**Comment by TheNeoGamer42** [comment]
partially was a joke, but yeah, alright

**Comment by Ms-Mee** [comment]
Pondering my morb

**Comment by TheNeoGamer42** [comment]
morbs your ius

**Pull request merged**
